// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRmbd8Ktux2kS-IIAnldRcom3LeMe2TyM',
    appId: '1:207086939648:web:9aa33cd76e9774b92b72e5',
    messagingSenderId: '207086939648',
    projectId: 'wikipets-b475a',
    authDomain: 'wikipets-b475a.firebaseapp.com',
    storageBucket: 'wikipets-b475a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgDikrPOBuhqTFM2EoFrDo8GdErfl_zJg',
    appId: '1:207086939648:android:291e8825123bee652b72e5',
    messagingSenderId: '207086939648',
    projectId: 'wikipets-b475a',
    storageBucket: 'wikipets-b475a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuo3YP_55CXzivPCdYz3LrabeeNw4iDpo',
    appId: '1:207086939648:ios:e6841b42977e25212b72e5',
    messagingSenderId: '207086939648',
    projectId: 'wikipets-b475a',
    storageBucket: 'wikipets-b475a.appspot.com',
    iosClientId: '207086939648-9s1m4vnk538a058fdrmmf72i1i7f1oav.apps.googleusercontent.com',
    iosBundleId: 'com.example.wikipets',
  );
}
